name = input("Enter your Name: ")
age = input("Enter your age: ")
first = int(input("Enter first number: "))
second = int(input("Enter second number: "))
print("The username is " + name + " and the age is " + age + "\nThe product is ", first * second)
